sudo: required
services:
        - docker
deploy:
        provider: elasticbeanstalk
        region: "ap-south-1"
        app: "docker-react"
        env: "Dockerreact-env-1"
        bucket_name: "elasticbeanstalk-ap-south-1-945194841046"
        bucket_path: "docker-react"
        on:
                branch: master
        access_key_id: "$AWS_ACCESS_KEY"
        secret_access_key: "$AWS_SECRET_KEY"


